### ISSUE TITLE
Saving Tag on a Page 500s

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#270]
When I pulled down to local, migrated, and tested it worked.

When I pushed to staging, migrated remotely and tested, it blew up. 
Specifically, I created a new page, added two tags "Foo, Bar" and saved.
This is the stack trace.

```
Started POST "/admin/pages" at 2017-01-29 19:12:47 +0000
Processing by Admin::PagesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"QD18dxg/eE/vY+RHtrelu91ZaFtxhe2wwClRprBnIm+5DTgLQIZDd/0xnde4QHY6R9G9J6vXzZj7z4asc5CT3g==", "page"=>{"title"=>"TEST", "subtitle"=>"", "content"=>"TESTTESTTESTTEST", "tweet"=>"", "summary"=>"", "slug"=>"", "published_at(1i)"=>"2017", "published_at(2i)"=>"1", "published_at(3i)"=>"29", "published_at(4i)"=>"19", "published_at(5i)"=>"12", "status_id"=>"1", "image"=>"", "image_description"=>"", "css"=>"", "hide_header"=>"0", "hide_footer"=>"0", "hide_layout"=>"0"}, "button"=>"", "tags"=>"Foo, Bar"}
  Redirect Load (1.5ms)  SELECT  "redirects".* FROM "redirects" WHERE "redirects"."source_path" = $1 ORDER BY "redirects"."id" DESC LIMIT $2  [["source_path", "/admin/pages"], ["LIMIT", 1]]
  Redirect Load (3.7ms)  SELECT  "redirects".* FROM "redirects" WHERE "redirects"."source_path" = $1 ORDER BY "redirects"."id" DESC LIMIT $2  [["source_path", "/admin/pages/"], ["LIMIT", 1]]
  Setting Load (2.8ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."slug" = $1 LIMIT $2  [["slug", :pinned_to_site_top_page_id], ["LIMIT", 1]]
  Setting Load (4.3ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."slug" = $1 LIMIT $2  [["slug", :pinned_to_footer_top_page_id], ["LIMIT", 1]]
  Setting Load (4.4ms)  SELECT  "settings".* FROM "settings" WHERE "settings"."slug" = $1 LIMIT $2  [["slug", :pinned_to_footer_bottom_page_id], ["LIMIT", 1]]
  User Load (3.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (1.1ms)  BEGIN
  Page Exists (1.2ms)  SELECT  1 AS one FROM "pages" WHERE "pages"."slug" = $1 LIMIT $2  [["slug", "test"], ["LIMIT", 1]]
  SQL (3.9ms)  INSERT INTO "pages" ("status_id", "title", "subtitle", "content", "image", "image_description", "css", "slug", "draft_code", "published_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "id"  [["status_id", 1], ["title", "TEST"], ["subtitle", ""], ["content", "TESTTESTTESTTEST"], ["image", ""], ["image_description", ""], ["css", ""], ["slug", "test"], ["draft_code", "dcc82d626ff954660e3304fcc1e9989c"], ["published_at", 2017-01-29 19:12:00 UTC], ["created_at", 2017-01-29 19:12:48 UTC], ["updated_at", 2017-01-29 19:12:48 UTC]]
   (1.9ms)  COMMIT
Redirected to /admin/pages/5
  Tag Load (1.3ms)  SELECT  "tags".* FROM "tags" WHERE "tags"."name" = $1 LIMIT $2  [["name", "Foo"], ["LIMIT", 1]]
  Tag Load (1.1ms)  SELECT  "tags".* FROM "tags" WHERE "tags"."name" = $1 LIMIT $2  [["name", "Bar"], ["LIMIT", 1]]
   (7.3ms)  BEGIN
   (2.6ms)  ROLLBACK
Completed 500 Internal Server Error in 87ms (ActiveRecord: 40.8ms)
** [Bugsnag] Notifying https://notify.bugsnag.com of ActiveModel::MissingAttributeError
  
ActiveModel::MissingAttributeError (can't write unknown attribute `taggable_id`):
  
app/models/tag.rb:19:in `assign_to!'

app/services/tag_assigner.rb:15:in `block in assign_tags_to!'
app/services/tag_assigner.rb:15:in `each'
app/services/tag_assigner.rb:15:in `assign_tags_to!'
app/controllers/admin/pages_controller.rb:62:in `organize_page'
app/middlewares/rack/redirect.rb:48:in `call'
```

***

To confirm, that Page tagging migration has been applied.

```
$: heroku run rake db:version
Current version: 20170125074852
```

**Comment by veganstraightedge** [comment]
@withoutboats

**Comment by withoutboats** [comment]
Based on the error tagging articles should fail as well. I can't repro locally & the only explanation I can think of is that the database actually hasn't been migrated properly contrary to what rake says. That version of the schema has a `taggable_id`.

**Comment by withoutboats** [comment]
Actually it looks like this is probably a caching issue: https://stackoverflow.com/questions/6820156/activemodelmissingattributeerror-occurs-after-deploying-and-then-goes-away-aft

**Comment by veganstraightedge** [comment]
Restarting the heroku app fixed this. Thanks for the caching link.
