### ISSUE TITLE
FIX: Intermittent spec failure

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#454]
# First run, all pass

```
> rspec
............................................................................................................................................................................................

Finished in 12.18 seconds (files took 2.8 seconds to load)
188 examples, 0 failures
```

# Second run, several fail

```
> rspec
WARN: Unresolved specs during Gem::Specification.reset:
      diff-lcs (< 2.0, >= 1.2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
...................................................FFF....................................................................................................................FFFFFFFFFF..F.....

Failures:

  1) Setting and changing an articles published_at date updating an existing article
     Failure/Error: expect(page).to have_content 'Logged in!'
       expected to find text "Logged in!" in "Retry later"
     # ./spec/spec_helper.rb:31:in `login_user'
     # ./spec/features/article_datetime_settings_spec.rb:38:in `block (2 levels) in <top (required)>'

  2) Setting and changing an articles published_at date Saving an article without entering publication date info
     Failure/Error:
       within('main') do
         fill_in 'username', with: 'user1'
         fill_in 'password', with: 'c'*31
       end

     Capybara::ElementNotFound:
       Unable to find visible css "main"
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/finders.rb:313:in `block in synced_resolve'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/finders.rb:37:in `find'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/session.rb:776:in `block (2 levels) in <class:Session>'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/session.rb:333:in `within'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/rspec/matcher_proxies.rb:14:in `within'
     # ./spec/spec_helper.rb:26:in `login_user'
     # ./spec/features/article_datetime_settings_spec.rb:62:in `block (2 levels) in <top (required)>'

  3) Setting and changing an articles published_at date Using 'PUBLISH NOW' feature
     Failure/Error:
       within('main') do
         fill_in 'username', with: 'user1'
         fill_in 'password', with: 'c'*31
       end

     Capybara::ElementNotFound:
       Unable to find visible css "main"
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/finders.rb:313:in `block in synced_resolve'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/node/finders.rb:37:in `find'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/session.rb:776:in `block (2 levels) in <class:Session>'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/session.rb:333:in `within'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # /Users/s/.gem/ruby/2.4.1/gems/capybara-2.15.1/lib/capybara/rspec/matcher_proxies.rb:14:in `within'
     # ./spec/spec_helper.rb:26:in `login_user'
     # ./spec/features/article_datetime_settings_spec.rb:81:in `block (2 levels) in <top (required)>'

  4) Pagination Redirects archives redirects on page 1
     Failure/Error: expect(response).to redirect_to("/2017/01/01/")

       Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
       Response body: Retry later
     # ./spec/requests/paginations_spec.rb:8:in `block (3 levels) in <top (required)>'

  5) Pagination Redirects archives redirects when no page number given
     Failure/Error: expect(response).to redirect_to("/2017/01/01/")

       Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
       Response body: Retry later
     # ./spec/requests/paginations_spec.rb:14:in `block (3 levels) in <top (required)>'

  6) Pagination Redirects categories redirects on page 1
     Failure/Error: expect(response).to redirect_to("/categories/slug/")

       Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
       Response body: Retry later
     # ./spec/requests/paginations_spec.rb:22:in `block (3 levels) in <top (required)>'

  7) Pagination Redirects categories redirects when no page number given
     Failure/Error: expect(response).to redirect_to("/categories/slug/")

       Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
       Response body: Retry later
     # ./spec/requests/paginations_spec.rb:28:in `block (3 levels) in <top (required)>'

  8) Pagination Redirects tags redirects on page 1
     Failure/Error: expect(response).to redirect_to("/tags/slug/")

       Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
       Response body: Retry later
     # ./spec/requests/paginations_spec.rb:36:in `block (3 levels) in <top (required)>'

  9) Pagination Redirects tags redirects when no page number given
     Failure/Error: expect(response).to redirect_to("/tags/slug/")

       Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
       Response body: Retry later
     # ./spec/requests/paginations_spec.rb:42:in `block (3 levels) in <top (required)>'

  10) Pagination Redirects videos redirects on page 1
      Failure/Error: expect(response).to redirect_to("/videos/")

        Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
        Response body: Retry later
      # ./spec/requests/paginations_spec.rb:50:in `block (3 levels) in <top (required)>'

  11) Pagination Redirects videos redirects when no page number given
      Failure/Error: expect(response).to redirect_to("/videos/")

        Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
        Response body: Retry later
      # ./spec/requests/paginations_spec.rb:56:in `block (3 levels) in <top (required)>'

  12) Pagination Redirects admin redirects on page 1
      Failure/Error: expect(response).to redirect_to("/admin/videos/")

        Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
        Response body: Retry later
      # ./spec/requests/paginations_spec.rb:64:in `block (3 levels) in <top (required)>'

  13) Pagination Redirects admin redirects when no page number given
      Failure/Error: expect(response).to redirect_to("/admin/videos/")

        Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
        Response body: Retry later
      # ./spec/requests/paginations_spec.rb:70:in `block (3 levels) in <top (required)>'

  14) Rack::Redirect doesn't redirect when not found
      Failure/Error: expect(response.status).to eq(200)

        expected: 200
             got: 429

        (compared using ==)
      # ./spec/requests/redirects_spec.rb:19:in `block (2 levels) in <top (required)>'

Finished in 8.15 seconds (files took 2.95 seconds to load)
188 examples, 14 failures

Failed examples:

rspec ./spec/features/article_datetime_settings_spec.rb:33 # Setting and changing an articles published_at date updating an existing article
rspec ./spec/features/article_datetime_settings_spec.rb:61 # Setting and changing an articles published_at date Saving an article without entering publication date info
rspec ./spec/features/article_datetime_settings_spec.rb:75 # Setting and changing an articles published_at date Using 'PUBLISH NOW' feature
rspec ./spec/requests/paginations_spec.rb:5 # Pagination Redirects archives redirects on page 1
rspec ./spec/requests/paginations_spec.rb:11 # Pagination Redirects archives redirects when no page number given
rspec ./spec/requests/paginations_spec.rb:19 # Pagination Redirects categories redirects on page 1
rspec ./spec/requests/paginations_spec.rb:25 # Pagination Redirects categories redirects when no page number given
rspec ./spec/requests/paginations_spec.rb:33 # Pagination Redirects tags redirects on page 1
rspec ./spec/requests/paginations_spec.rb:39 # Pagination Redirects tags redirects when no page number given
rspec ./spec/requests/paginations_spec.rb:47 # Pagination Redirects videos redirects on page 1
rspec ./spec/requests/paginations_spec.rb:53 # Pagination Redirects videos redirects when no page number given
rspec ./spec/requests/paginations_spec.rb:61 # Pagination Redirects admin redirects on page 1
rspec ./spec/requests/paginations_spec.rb:67 # Pagination Redirects admin redirects when no page number given
rspec ./spec/requests/redirects_spec.rb:16 # Rack::Redirect doesn't redirect when not found
```

**Comment by veganstraightedge** [comment]
Not sure if this is just me or if I did something to cause it. Or if it's intermittent for everyone.

**Comment by shushugah** [comment]
This may be obvious, but have you tried `bundle exec rspec` ? If it's selecting wrong gems, you can also remove non relevant gems with `bundle install --clean`

**Comment by astronaut-wannabe** [comment]
I got this too after 4-5 repeated runs (@shushugah, even with `bundle exec rspec`)

@veganstraightedge if you look at the failed specs they are all something like:
```sh
Expected response to be a <3XX: redirect>, but was a <429: Too Many Requests>
```

pretty sure this is rack-attack detecting the test suite as a ddos.

Will look into how to disable `rack-attack` in `test`
