### ISSUE TITLE
Unable to run setup script in ubuntu

### ISSUE THREAD

**Issue by greggawatt** [crimethinc/website#601]
Hey sorry to bother but I got a new computer running ubuntu that i'm trying to get things running on and i'm hitting this error:
```
gregg@goldman:~/Development/website$ ./script/setup
==> Installing Bundler...
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 2 seconds
1 gem installed
==> Installing gem dependencies...
==> Setting up DB...
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:drop => db:check_protected_environments
(See full trace by running task with --trace)
```

Any ideas? Googling is talking about TCP and i don't really know what I need to do

**Comment by greggawatt** [comment]
i edited database.yml
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: ''
  database: crimethinc_development

test:
  <<: *default
  host: ''
  database: crimethinc_test

```

so now it correctly creates the database, now i'm hitting another issue with one of the migrations
```
gregg@goldman:~/Development/website$ rake db:migrate
== 20170517041238 CreateSearchResults: migrating ==============================
-- create_view(:search_results, {:materialized=>true})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedFunction: ERROR:  function array_to_tsvector(character varying[]) does not exist
LINE 10:   setweight(array_to_tsvector(tag_names), 'D') ||
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: CREATE MATERIALIZED VIEW "search_results" AS SELECT
  searchable_id, searchable_type, title, subtitle, content,
  tag_names AS tag,
  category_names AS category,
  contributor_names AS contributor,

  setweight(title, 'A') ||
  setweight(subtitle, 'B') ||
  setweight(content, 'C') ||
  setweight(array_to_tsvector(tag_names), 'D') ||
  setweight(array_to_tsvector(category_names), 'D') ||
  setweight(array_to_tsvector(contributor_names), 'D') AS document

  FROM (
    SELECT
      articles.id AS searchable_id,
      'Article' AS searchable_type,
      to_tsvector(coalesce(articles.title, '')) AS title,
      to_tsvector(coalesce(articles.subtitle, '')) AS subtitle,
      to_tsvector(coalesce(articles.content, '')) AS content,
      CASE WHEN COUNT(tags) = 0 THEN ARRAY[]::text[] ELSE array_agg(tags.name) END AS tag_names,
      CASE WHEN COUNT(categories) = 0 THEN ARRAY[]::text[] ELSE array_agg(categories.name) END AS category_names,
      CASE WHEN COUNT(contributors) = 0 THEN ARRAY[]::text[] ELSE array_agg(contributors.name) END AS contributor_names
    FROM articles
    INNER JOIN statuses ON statuses.id = articles.status_id AND statuses.name='published'
    LEFT JOIN taggings ON taggings.taggable_id = articles.id AND taggings.taggable_type = 'Article'
    LEFT JOIN tags ON tags.id = taggings.tag_id
    LEFT JOIN categorizations ON categorizations.article_id = articles.id
    LEFT JOIN categories ON categories.id = categorizations.category_id
    LEFT JOIN contributions ON contributions.article_id = articles.id
    LEFT JOIN contributors ON contributors.id = contributions.contributor_id
    WHERE articles.published_at < now()
    GROUP BY searchable_id, searchable_type

    UNION

    SELECT
      pages.id AS searchable_id,
      'Page' AS searchable_type,
      to_tsvector(coalesce(pages.title, '')) AS title,
      to_tsvector(coalesce(pages.subtitle, '')) AS subtitle,
      to_tsvector(coalesce(pages.content, '')) AS content,
      CASE WHEN COUNT(tags) = 0 THEN ARRAY[]::text[] ELSE array_agg(tags.name) END AS tag_names,
      ARRAY[]::text[] AS category_names,
      ARRAY[]::text[] AS contributor_names
    FROM pages
    INNER JOIN statuses ON statuses.id = pages.status_id AND statuses.name='published'
    LEFT JOIN taggings ON taggings.taggable_id = pages.id AND taggings.taggable_type = 'Page'
    LEFT JOIN tags ON tags.id = taggings.tag_id
    WHERE pages.published_at < now()
    GROUP BY searchable_id, searchable_type

    UNION

    SELECT
      episodes.id AS searchable_id,
      'Episode' AS searchable_type,
      to_tsvector(coalesce(episodes.title, '')) AS title,
      to_tsvector(coalesce(episodes.subtitle, '')) AS subtitle,
      to_tsvector(coalesce(episodes.content, '')) AS content,
      ARRAY[]::text[] AS tag_names,
      ARRAY[]::text[] AS category_names,
      ARRAY[]::text[] AS contributor_names
    FROM episodes
    GROUP BY searchable_id, searchable_type
  ) AS a;
;
/home/gregg/Development/website/db/migrate/20170517041238_create_search_results.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function array_to_tsvector(character varying[]) does not exist
LINE 10:   setweight(array_to_tsvector(tag_names), 'D') ||
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: CREATE MATERIALIZED VIEW "search_results" AS SELECT
  searchable_id, searchable_type, title, subtitle, content,
  tag_names AS tag,
  category_names AS category,
  contributor_names AS contributor,

  setweight(title, 'A') ||
  setweight(subtitle, 'B') ||
  setweight(content, 'C') ||
  setweight(array_to_tsvector(tag_names), 'D') ||
  setweight(array_to_tsvector(category_names), 'D') ||
  setweight(array_to_tsvector(contributor_names), 'D') AS document

  FROM (
    SELECT
      articles.id AS searchable_id,
      'Article' AS searchable_type,
      to_tsvector(coalesce(articles.title, '')) AS title,
      to_tsvector(coalesce(articles.subtitle, '')) AS subtitle,
      to_tsvector(coalesce(articles.content, '')) AS content,
      CASE WHEN COUNT(tags) = 0 THEN ARRAY[]::text[] ELSE array_agg(tags.name) END AS tag_names,
      CASE WHEN COUNT(categories) = 0 THEN ARRAY[]::text[] ELSE array_agg(categories.name) END AS category_names,
      CASE WHEN COUNT(contributors) = 0 THEN ARRAY[]::text[] ELSE array_agg(contributors.name) END AS contributor_names
    FROM articles
    INNER JOIN statuses ON statuses.id = articles.status_id AND statuses.name='published'
    LEFT JOIN taggings ON taggings.taggable_id = articles.id AND taggings.taggable_type = 'Article'
    LEFT JOIN tags ON tags.id = taggings.tag_id
    LEFT JOIN categorizations ON categorizations.article_id = articles.id
    LEFT JOIN categories ON categories.id = categorizations.category_id
    LEFT JOIN contributions ON contributions.article_id = articles.id
    LEFT JOIN contributors ON contributors.id = contributions.contributor_id
    WHERE articles.published_at < now()
    GROUP BY searchable_id, searchable_type

    UNION

    SELECT
      pages.id AS searchable_id,
      'Page' AS searchable_type,
      to_tsvector(coalesce(pages.title, '')) AS title,
      to_tsvector(coalesce(pages.subtitle, '')) AS subtitle,
      to_tsvector(coalesce(pages.content, '')) AS content,
      CASE WHEN COUNT(tags) = 0 THEN ARRAY[]::text[] ELSE array_agg(tags.name) END AS tag_names,
      ARRAY[]::text[] AS category_names,
      ARRAY[]::text[] AS contributor_names
    FROM pages
    INNER JOIN statuses ON statuses.id = pages.status_id AND statuses.name='published'
    LEFT JOIN taggings ON taggings.taggable_id = pages.id AND taggings.taggable_type = 'Page'
    LEFT JOIN tags ON tags.id = taggings.tag_id
    WHERE pages.published_at < now()
    GROUP BY searchable_id, searchable_type

    UNION

    SELECT
      episodes.id AS searchable_id,
      'Episode' AS searchable_type,
      to_tsvector(coalesce(episodes.title, '')) AS title,
      to_tsvector(coalesce(episodes.subtitle, '')) AS subtitle,
      to_tsvector(coalesce(episodes.content, '')) AS content,
      ARRAY[]::text[] AS tag_names,
      ARRAY[]::text[] AS category_names,
      ARRAY[]::text[] AS contributor_names
    FROM episodes
    GROUP BY searchable_id, searchable_type
  ) AS a;
;
/home/gregg/Development/website/db/migrate/20170517041238_create_search_results.rb:3:in `change'

Caused by:
PG::UndefinedFunction: ERROR:  function array_to_tsvector(character varying[]) does not exist
LINE 10:   setweight(array_to_tsvector(tag_names), 'D') ||
                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
/home/gregg/Development/website/db/migrate/20170517041238_create_search_results.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by greggawatt** [comment]
The version shipping with ubuntu 16.04 is 9.5. Following the instructions here:
https://www.postgresql.org/download/linux/ubuntu/
I upgraded to postgres 10 and still had the issue.

**Comment by greggawatt** [comment]
The version shipping with ubuntu 16.04 is 9.5. Following the instructions here:
https://www.postgresql.org/download/linux/ubuntu/
I upgraded to postgres 10 and still had the issue. 
```
➜  website git:(master) ✗ psql -V       
psql (PostgreSQL) 10.1
```

**Comment by greggawatt** [comment]
@veganstraightedge do you know the version of postgresql we are using in prod?

**Comment by greggawatt** [comment]
Nevermind, I found the missing function was introduced in 9.6. I fully uninstalled 9.5 and made sure it was running on the right port and now we are good.

If anyone ever needs help running the environment on ubuntu let me know lol
