### ISSUE TITLE
G20 live blog post is 500ing

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#788]
# 500 error:

https://crimethinc.com/2017/07/05/announcing-continuous-live-coverage-of-the-g20-in-hamburg-with-an-update-from-the-clashes-of-july-4

***

```json
params: {
  "controller": "articles",
  "action": "show",
  "year": "2017",
  "month": "07",
  "day": "05",
  "slug": "announcing-continuous-live-coverage-of-the-g20-in-hamburg-with-an-update-from-the-clashes-of-july-4"
}
```

```json
headers
{
  "Version": "HTTP/1.1",
  "Host": "crimethinc.com",
  "Connection": "close",
  "Accept": "*/*",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)",
  "Accept-Encoding": "gzip",
  "X-Request-Id": "0807d054-4179-4bb1-b07d-f9545bb994f4",
  "X-Forwarded-For": "17.58.99.196",
  "X-Forwarded-Proto": "https",
  "X-Forwarded-Port": "443",
  "Via": "1.1 vegur",
  "Connect-Time": "0",
  "X-Request-Start": "1530292448426",
  "Total-Route-Time": "0"
}
```

***

```
vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.0/lib/active_model/attribute.rb:207:in `with_value_from_database': can't write unknown attribute `parent_id` (ActionView::Template::Error)
    from app/views/articles/show.html.erb:26:in `block (2 levels) in _app_views_articles_show_html_erb__1324778530118940859_69921099215960'
    from app/helpers/articles_helper.rb:43:in `article_tag'
    from app/views/articles/show.html.erb:12:in `block in _app_views_articles_show_html_erb__1324778530118940859_69921099215960'
    from app/views/articles/show.html.erb:1:in `_app_views_articles_show_html_erb__1324778530118940859_69921099215960'
    from vendor/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
    from app/controllers/articles_controller.rb:50:in `show'
    from app/middlewares/rack/redirect.rb:40:in `call'
    from app/middlewares/rack/blog_redirect.rb:15:in `call'
    from app/middlewares/rack/apex_redirect.rb:15:in `call'
    from app/middlewares/rack/domain_redirect.rb:16:in `call'

Caused by: vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.0/lib/active_model/attribute.rb:207:in `with_value_from_database': can't write unknown attribute `parent_id` (ActiveModel::MissingAttributeError)
    from app/views/articles/show.html.erb:26:in `block (2 levels) in _app_views_articles_show_html_erb__1324778530118940859_69921099215960'
    from app/helpers/articles_helper.rb:43:in `article_tag'
    from app/views/articles/show.html.erb:12:in `block in _app_views_articles_show_html_erb__1324778530118940859_69921099215960'
    from app/views/articles/show.html.erb:1:in `_app_views_articles_show_html_erb__1324778530118940859_69921099215960'
    from vendor/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
    from app/controllers/articles_controller.rb:50:in `show'
    from app/middlewares/rack/redirect.rb:40:in `call'
    from app/middlewares/rack/blog_redirect.rb:15:in `call'
    from app/middlewares/rack/apex_redirect.rb:15:in `call'
    from app/middlewares/rack/domain_redirect.rb:16:in `call'
```

<img width="991" alt="screen shot 2018-06-29 at 10 54 19 am" src="https://user-images.githubusercontent.com/4361/42107128-1802bec2-7b8b-11e8-9e64-df5228b9c596.png">

**Comment by veganstraightedge** [comment]
https://github.com/crimethinc/website/commit/795e502cda44028de2cbcad4560e75fdff3c4e69
